### ISSUE TITLE
Issues with creating an RFI Survey

### ISSUE THREAD

**Issue by CEverest-RFI** [0xCoto/Virgo#13]
Hi
I have been having issues with trying to get an RFI plot using Virgo. I tried using .plot_rfi but get the error:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "Testrfi2.py", line 18, in <module>
    virgo.plot_rfi(rfi_parameters=rfi, data='rfi_data', dB=True, plot_file='plot.png')
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/virgo.py", line 981, in plot_rfi
    import matplotlib
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import

I tried using virgo.observe and virgo.plot, and then  but get the error:

Traceback (most recent call last):
  File "Test.py", line 17, in <module>
    virgo.observe(obs_parameters=obs, obs_file='observation.dat')
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/virgo.py", line 551, in observe
    duration=duration, t_sample=t_sample, obs_file=obs_file)
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/run_wola.py", line 51, in __init__
    self.osmosdr_source_0 = osmosdr.source( args="numchan=" + str(1) + " " + dev_args )
  File "/usr/local/lib/python3/dist-packages/osmosdr/osmosdr_swig.py", line 1162, in make
    return _osmosdr_swig.source_make(*args, **kwargs)
RuntimeError: No supported devices found (check the connection and/or udev rules).

The same happens with rfi_monitor.
So part of the issue seems to be that the device is unsupported with the source block, but the osmocom Source in the wola.grc says it supports the SDR I have. 

I am on a raspberry pi 4, using the PiSDR image, with Virgo version 3.6.6, and using a SDRplay RSPdx, with an Omnilog 90200 antenna.

The code is below:

`import virgo

# Define observation parameters
obs = {
    'dev_args': '',
    'rf_gain': 30,
    'if_gain': 25,
    'bb_gain': 18,
    'frequency': 1420e6,
    'bandwidth': 2.4e6,
    'channels': 2048,
    't_sample': 1,
    'duration': 60
}

# Define rfi survey parameters
rfi = {
    'dev_args': '',
    'rf_gain': 30,
    'if_gain': 25,
    'bb_gain': 18,
    'frequency': 1420e6,
    'bandwidth': 2.4e6,
    'channels': 2048,
    't_sample': 1,
    'duration': 60,
    'f_lo': 1400e6
}

virgo.observe(obs_parameters=obs, obs_file='observation.dat')

# Analyze data, mitigate RFI and export the data as a CSV file
virgo.plot(obs_parameters=obs, n=20, m=35, f_rest=1420.4057517667e6,
           obs_file='observation.dat', rfi=[1419.2e6, 1419.3e6],
           dB=True, spectra_csv='spectrum.csv', plot_file='plot.png')

# Begin data acquisition
virgo.plot_rfi(rfi_parameters=rfi, data='rfi_data', dB=True, plot_file='plot.png')
`

Thanks for your help

**Comment by 0xCoto** [comment]
Looks like we'll have to resolve the `virgo.observe` issue first, as the rest of the problems are definitely dependent on the acquisition of the data. The [osmocom documentation](https://osmocom.org/projects/gr-osmosdr/wiki#SDRplay-Source) includes some information on interfacing between your SDRplay device and GNU Radio.

Perhaps @luigifcruz can give an input as to whether SDRplay devices have been tested with PiSDR (or e.g. if a Soapy Source shall be used instead)?

What happens if you set `'dev_args': 'sdrplay'`?

**Comment by CEverest-RFI** [comment]
It comes up with the same error, 'No supported devices found'. I've tried rebuilding GrOsmoSDR, as in the documentation it says to build it using the parameter -DENABLE_NONFREE=TRUE to enable the driver, and get an error:

-- Build type not specified: defaulting to release.
CMake Error at CMakeLists.txt:45 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.9".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.2.0



-- Configuring incomplete, errors occurred!
See also "/home/pi/Desktop/gr-osmosdr/build/CMakeFiles/CMakeOutput.log".

Although I'm not sure whether this is worth doing as I'm not sure how GrOsmoSDR is installed on the PiSDR image in the first place.

**Comment by 0xCoto** [comment]
Have you got a 'Soapy SDR Source' block available in GNU Radio?

**Comment by luigifcruz** [comment]
@0xCoto I'm not sure if I can help. I don't have experience with the SDRplay SDK. The current release of PiSDR does not support the device yet. The manufacturer sent me a unit for integration but it didn't arrive yet. I'm planning to add full support in the next major release coming soon.

**Comment by luigifcruz** [comment]
Maybe worth taking a look if the UDEV rules for the SDRplay were installed since the logs are mentioning that no device was found. This generally happens on `make install` when a certain flag is passed to CMake.

**Comment by CEverest-RFI** [comment]
I do have a Soapy Source, but not specifically a Soapy SDR Source. I've tried replacing the source with the Soapy Source though, and set the drivers as sdrplay, but get the same error. As for the UDEV rules, where should I be looking, and what should I be looking for? I can find the 80-drivers.rules file, but that doesn't have any mention of SDRPlay.

I did find an official pi image by SDRplay, and in the description, it does say that GNU Radio source blocks are not avaliable yet for the RSPdx, so I'm not entirely sure theres anything that can be done until the image is updated.

**Comment by 0xCoto** [comment]
I remember having success getting an SDRplay device to work with Virgo (with `gr-osmosdr`), but it was a bit tricky to set up because their drivers are a bit outdated/incompatible with GNU Radio ≥3.8. Since you're using a somewhat semi-unsupported device, I'd suggest trying to downgrade to GNU Radio 3.7 and installing the [drivers provided by SDRplay](https://www.sdrplay.com/downloads/).

**Comment by CEverest-RFI** [comment]
After having a look around, I decided to try updating gnuradio to 3.9, and installing the following to see if I could use the soapy block, and it seems to recognise and accept the RSPdx when testing:

https://github.com/pothosware/SoapySDRPlay3

although I am having another issue, but i'm not sure whether it would better to contact them, as I'm not sure whether the issue is with me misconfiguring the block or something else:

TypeError: primitive_connect(): incompatible function arguments. The following argument types are supported:
    1. (self: gnuradio.gr.gr_python.hier_block2_pb, block: gnuradio.gr.gr_python.basic_block) -> None
    2. (self: gnuradio.gr.gr_python.hier_block2_pb, src: gnuradio.gr.gr_python.basic_block, src_port: int, dst: gnuradio.gr.gr_python.basic_block, dst_port: int) -> None

Invoked with: <gnuradio.gr.gr_python.top_block_pb object at 0xb5bf0ce0>, <Swig Object of type 'gr::basic_block_sptr *' at 0xb5b30ef0>, 0, <gnuradio.gr.gr_python.basic_block object at 0xb1561300>, 0

**Comment by luigifcruz** [comment]
> As for the UDEV rules, where should I be looking, and what should I be looking for?

@CEverest-RFI Sorry for the delay. This PDF (page 4) details the installation process of the UDEV rules for SDR Play. https://sdrplay.com/docs/Mirics_SDR_API_Linux_install_technote_r1p1.pdf

**Comment by CEverest-RFI** [comment]
I think there may be an issue with changing the source block, as I've managed to get a SoapySDR source block working with with the SDR, but changing any of the files, such as ftf.grc or wola.grc is not easily done due to permissions, but even when done (by copying them out of the folder then sudo mv them back in), the other files such as run_ftf.py are written assuming the osmosdr source block is in use, so even getting the correct source block would not be able to fix it without rewriting run_ftf.py and run_wola.py.

**Comment by 0xCoto** [comment]
Yeah, that makes sense. Your logic to sudo mv the grc files to the package directory is completely fair, but before you do that, open the grc and recompile (run the flowcharts). You'll probably have to rename the .py files to match run_ftf.py and run_wola.py, but other than that, replacing all 4 files (sudo mv to the package directory) should do the trick.

**Comment by CEverest-RFI** [comment]
I tried regenerating the flow graphs, then sudo mv into the directory, but it can't seem to find run_wola:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/virgo.py", line 514, in observe
    from run_wola import run_observation
ModuleNotFoundError: No module named 'run_wola'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Test2.py", line 17, in <module>
    virgo.observe(obs_parameters=obs, obs_file='observation.dat')
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/virgo.py", line 516, in observe
    from .run_wola import run_observation
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/run_wola.py", line 29
    def __init__(self, bandwidth=2e6, bb_gain=20, channels=1024, dev_args=, duration=60, frequency=1420e6, if_gain=20, obs_file=observation.dat, rf_gain=30, t_sample=1):
                                                                          ^
SyntaxError: invalid syntax

And there seems to be the other issue of this syntax. The formatting of the error is a bit wrong on here, the ^ should be underneath the end of  dev_args=,

I then tried setting dev_args=0 (as in the .grc's they have a dev_args=0 variable, but I'm not sure whether thats the correct thing to do), but get the following error:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/virgo.py", line 514, in observe
    from run_wola import run_observation
ModuleNotFoundError: No module named 'run_wola'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Test2.py", line 17, in <module>
    virgo.observe(obs_parameters=obs, obs_file='observation.dat')
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/virgo.py", line 516, in observe
    from .run_wola import run_observation
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/run_wola.py", line 27, in <module>
    class run_observation(gr.top_block):
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/run_wola.py", line 29, in run_observation
    def __init__(self, bandwidth=2e6, bb_gain=20, channels=1024, dev_args=0, duration=60, frequency=1420e6, if_gain=20, obs_file=observation.dat, rf_gain=30, t_sample=1):
NameError: name 'observation' is not defined

**Comment by 0xCoto** [comment]
For the syntax error, it seems to be a GR version issue (I'm planning to push a fix for this soon). Open the flowcharts and change dev_args and obs_file from Type: None to Type: String and re-compile.

When you compile run_ftf.grc you should see a run_observation.py get generated. Rename that to run_ftf.py and sudo mv the file to the installation directory. Do the same for run_wola.grc, but rename it to run_wola.py before sudo mv'ing. See if that works.

**Comment by CEverest-RFI** [comment]
I did that, and managed to get the .observe and .plot functions to work:

![plot](https://user-images.githubusercontent.com/82085184/116822966-a4d8db80-ab79-11eb-8b54-ed5f1bc40355.png)

Although I'm using a small omnidirectional antenna, so I'm not sure whether any of the plot would be useful, apart from that gap in data on the left, which seems to occur every time its run.

I still can't get .monitor_rfi to work though, I just get the following error:

Traceback (most recent call last):
  File "Test2.py", line 17, in <module>
    virgo.monitor_rfi(1415e6, 1425e6, obs_parameters=obs, data='rfi_data')
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/virgo.py", line 1118, in monitor_rfi
    observe(obs_parameters=rfi_parameters, spectrometer='ftf', obs_file=data+'/'+str(i)+'.dat')
  File "/home/pi/.local/lib/python3.7/site-packages/virgo/virgo.py", line 511, in observe
    from .run_ftf.py import run_observation
ModuleNotFoundError: No module named 'virgo.run_ftf.py'; 'virgo.run_ftf' is not a package

**Comment by 0xCoto** [comment]
The gap is essentially masked RFI channels (manually input by the user). If you don't want to mask anything, check the virgo.plot parameters: you just have to get rid of the rfi=[...] argument.

As for the other error, it's not quite clear why it would occur, since virgo.monitor_rfi basically calls virgo.observe. It appears like it can't find run_ftf.py, but you're saying virgo.observe works fine?

Are you running everything with the same Python from the same script? What happens if you virgo.observe and then virgo.monitor_rfi in the same script? Does the first command succeed and the second fail?

(By the way make sure you don't have any local scripts or directories named 'virgo', as this may often confuse Python that you're trying to import a local module)

**Comment by CEverest-RFI** [comment]
I get the same error with both in the same script. The first command seems to succeed, as I get a observation.dat and observation.header file out.
One thing I forgot to mention, was that when i first ran the python scripts, I got the ImportError: No module name virgo. So I used pip install astro-virgo (for both versions of python). Which gave me another copy of virgo in at:

/home/pi/.local/lib/python3.7/site-packages/virgo

Which was the one I modified, as when running the script this was the folder it seemed to run the .grc files from. Not sure whether that could be related or not, though.

**Comment by CEverest-RFI** [comment]
Hi, just wondering if there is any update, or anything I can do that might help with diagnosing the issue?

**Comment by 0xCoto** [comment]
Hi @CEverest-RFI - Sorry for th late reply. Are you running everything from the same Python?

**Comment by 0xCoto** [comment]
Also, please share a screenshot of what the modified WOLA and FTF flowcharts look like.

**Comment by CEverest-RFI** [comment]
Yes, I am running it all from the same python, which is python 3.7, as far as I can tell. The WOLA and FTF flowcharts are below:

![2021-05-21-174941_2560x1440_scrot](https://user-images.githubusercontent.com/82085184/119171898-1d3a0a80-ba5d-11eb-83a6-8d4a683ed32d.png)

![2021-05-21-174944_2560x1440_scrot](https://user-images.githubusercontent.com/82085184/119171918-24611880-ba5d-11eb-9920-9ffbb2f46cfb.png)

**Comment by 0xCoto** [comment]
In case anyone's wondering, the issue ended up being some (accidental) modification of `virgo.py`, these lines in particular:
```python
if spectrometer.lower() != 'wola':
    try:
        from run_ftf import run_observation
    except:
        from .run_ftf import run_observation
```
tried to load `run_ftf.py` instead of `run_ftf`. The file must have been named `run_ftf.py.py` to work.
