### ISSUE TITLE
unexpected keyword argument 'catch_exceptions'

### ISSUE THREAD

**Issue by islandmonkey** [0xCoto/Virgo#31]
Installed Virgo as per instructions and got the following error when I run virgo.observe:

```
>> virgo.observe(obs_parameters=obs, obs_file='observation.dat')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mo/.local/lib/python3.8/site-packages/virgo/virgo.py", line 557, in observe
    observation = run_observation(dev_args=dev_args, frequency=frequency, bandwidth=bandwidth, rf_gain=rf_gain,
  File "/home/mo/.local/lib/python3.8/site-packages/virgo/run_wola.py", line 31, in __init__
    gr.top_block.__init__(self, "Run Observation", catch_exceptions=True)
TypeError: __init__() got an unexpected keyword argument 'catch_exceptions'
```
Followed the example in the instructions.

**Comment by islandmonkey** [comment]
Ubuntu 20.04.5 LTS 
GNU Radio 3.8.1.0

**Comment by islandmonkey** [comment]
removed catch_exception which started gr-osmosdr but now i'm getting a segmentaion fault:
```
>>> virgo.observe(obs_parameters=obs, obs_file='observation.dat')
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.1.0
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
[INFO] Using format CF32.
Segmentation fault
```
I'm using an Adalm Pluto SDR and i just found out that it is not supported by gr-osmosdr. Is this correct? Is this causing the issues maybe?

**Comment by ewsandor** [comment]
I can second the original `TypeError: __init__() got an unexpected keyword argument 'catch_exceptions'` issue while trying to setup Virgo on a Raspberry Pi 3 B+.

I am observing this issue with a fresh installation of the 64-bit Raspberry Pi OS (Debian 11 based) with Python 3.9.2 and GNU Radio 3.8.2.0 installed through apt.  I installed Virgo 3.8.2 through pip.

Manually removing catch_exception=... from my local installation did work for me though (no segfault).  

Just documenting here in case anyone else experiences this issue on a Raspberry Pi as well.

**Comment by helmick43270** [comment]
I just commented out catch_exceptions=True) in line 31 of run_wola.py, and ended the call with a parenthesis, so it just has one argument. Now virgo.observe seems to be working okay. It’s as though the second argument is not valid. I don’t claim to know much about it, and maybe I’m saying the same thing as ewsandor. I think I read ewsandor’s comment, tried it, then forgot I read it. Anyway, I’m using an Intel iMac running Linux Mint based on Ubuntu 20.04, and an rtl-sdr dongle.
